### ISSUE TITLE
If using Colab: `aria2` may need to be installed first

### ISSUE THREAD

**Issue by tzmartin** [camenduru/TRELLIS-jupyter#1]
```
%%capture
! sudo apt-get install aria2
```

**Comment by LucasSilvaFerreira** [comment]
@tzmartin, Did you figure out how to run it? I had other problems with colab.

**Comment by LucasSilvaFerreira** [comment]
![image](https://github.com/user-attachments/assets/d147cb11-f8b2-44af-94bd-17ffd525be0b)
I'm stuck in this part! Some ninja problem. Something related to tensorviewer

**Comment by camenduru** [comment]
thanks @tzmartin ❤

**Comment by camenduru** [comment]
@LucasSilvaFerreira please try this: https://x.com/camenduru/status/1864937307632988321
